# Check automatically, after pushing on main, the build of Hugo site
name: Auto Check Build

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      withDeployment:
        description: 'Tells the built website must be deployed on the handbook-test'
        required: false
        default: true
        type: boolean

      targetRepository:
        description: 'The target repository where the website must be deployed to.'
        required: false
        default: 'spiges/handbook-test'
        type: string

      targetBranch:
        description: 'The target branch in ''targetRepository'' where the website must be deployed to.'
        required: false
        default: 'main'
        type: string

      withTargetHistoryKept:
        description: 'Tells the Git history of ''targetBranch@targetRepository'' must be kept'
        required: false
        default: false
        type: boolean

      deployedBaseUrl:
        description: 'The base-URL from which the deployed website is reachable'
        required: false
        default: 'https://spiges.github.io/handbook-test/'
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
        HUGO_VERSION: 0.122.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb    

      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Clear npm cache
        run: npm cache clean --force
          
      - name: Install Node.js dependencies with npm ci
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
            hugo \
                --gc \
                --minify \
                --baseURL "${{ github.event.inputs.deployedBaseUrl }}"

      - name: Deploy to the specified environment
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: ${{ github.event.inputs.targetBranch }}
          build_dir: public
          repo: ${{ github.event.inputs.targetRepository }}
          keep_history: ${{ github.event.inputs.withTargetHistoryKept }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
