# Check automatically, after pushing on main, the build of Hugo site
name: Auto Check Build

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      withDeployment:
        description: 'The built website must be deployed'
        required: false
        default: true
        type: boolean

      targetRepository:
        description: 'The target repository where the website must be deployed to.'
        required: false
        default: 'spiges/handbook-test'
        type: string

      targetBranch:
        description: 'The target branch in ''targetRepository'' where the website must be deployed to.'
        required: false
        default: 'main'
        type: string

      withTargetHistoryKept:
        description: 'Tells the Git history of ''targetBranch@targetRepository'' must be kept'
        required: false
        default: false
        type: boolean

      deployedBaseUrl:
        description: 'The base-URL from which the deployed website is reachable'
        required: false
        default: 'https://spiges.github.io/handbook-test/'
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
        HUGO_VERSION: 0.122.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb    

      - name: Install Dart Sass Embedded
        if: success()
        run: sudo snap install dart-sass-embedded

      - name: Checkout
        if: success()
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        if: success()
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Clear npm cache
        if: success()
        run: npm cache clean --force
          
      - name: Install Node.js dependencies with npm ci
        if: success()
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Update baseURL in hugo.toml
        if: success()
        run: |
          baseURL=${{ github.event.inputs.deployedBaseUrl }}
          sed -i "s|baseURL[[:space:]]*=[[:space:]]*'.*'|baseURL = '$baseURL'|" hugo.toml

      - name: Update buildDatetime in hugo.toml
        if: success()
        run: |
          buildDatetime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s/buildDatetime[[:space:]]*=[[:space:]]*\".*\"/buildDatetime = \"$buildDatetime\"/" hugo.toml

      - name: Update gitHash in hugo.toml
        if: success()
        run: |
          gitHash=$(git rev-parse --short HEAD)
          echo "git hash: $gitHash" 
          sed -i "s/gitHash[[:space:]]*=[[:space:]]*\".*\"/gitHash = \"$gitHash\"/" hugo.toml

      - name: Update version in hugo.toml
        if: success()
        run: |
          version=$(grep 'version[[:space:]]*=' hugo.toml | sed 's/version[[:space:]]*=[[:space:]]*"\([^"]*\)"/\1/')
          echo "Current version: $version"

          branch_name=$(echo $GITHUB_REF | sed 's|refs/heads/||')
          echo "Current branch: $branch_name" 
          new_version="${version}-${branch_name}"
          echo "New version: $new_version"
          sed -i "s|version[[:space:]]*=[[:space:]]*\"${version}\"|version = \"${new_version}\"|" hugo.toml
          
      - name: Update $ob-venetian-red in assets/scss/_variables_project.scss
        if: success()
        run: |
          sed -i "s|\$ob-venetian-red:[[:space:]]*#.*;|\$ob-venetian-red: #004ddc;|" assets/scss/_variables_project.scss

      - name: Build with Hugo
        if: success()
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
            hugo \
                --gc \
                --minify \
                --baseURL "${{ github.event.inputs.deployedBaseUrl }}"

      - name: Copy README.md and LICENSE.md files in public directory
        if: success()
        run: |
          echo "This repository contents the built SpiGes-Documentation project website for testing" > README.md
          cp README.md public/
          cp LICENSE.md public/

      - name: Deploy to the specified environment
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: ${{ github.event.inputs.targetBranch }}
          build_dir: public
          repo: ${{ github.event.inputs.targetRepository }}
          keep_history: ${{ github.event.inputs.withTargetHistoryKept }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
