# Check build after pushing on main, during Pull-Request, or manually with any branch, with optional deployment on test environment
name: Check Build

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploymentEnabled:
        description: "The built website must be deployed"
        required: false
        default: true
        type: boolean

env:
  TARGET_REPOSITORY: "spiges/handbook-test"
  TARGET_BRANCH: "main"
  KEEP_TARGET_HISTORY: false
  DEPLOYED_BASE_URL: "https://spiges.github.io/handbook-test/"
  DEPLOYED_BASE_NAME: "handbook-test"
  # Versions
  HUGO_VERSION: "0.124.1"
  GO_VERSION: "1.22.2"
  NODE_VERSION: "20.12.1"
  DART_SASS_VERSION: "latest/stable" # Only one stable version available through Snap. It is not possible to select a specific version for an extended period.

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  markdownLintCheck:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Markdown Lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: "**/*.md"
          output: ".markdownlintresult"
        id: lint
        continue-on-error: true

      - name: Upload markdownlint result as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdownlint-results
          path: .markdownlintresult

      - name: Generate Annotations and Check Warning Threshold
        run: |
          warning_count=0
          threshold=5  # Set the warning threshold here
          regex='^([^:]+):([0-9]+):([0-9]+:)?\s+(.+)$'

          while IFS= read -r line; do
            if [[ $line =~ $regex ]]; then
              filename=${BASH_REMATCH[1]}
              line_number=${BASH_REMATCH[2]}
              message=${BASH_REMATCH[4]}
              # Display as a warning
              echo "::warning file=$filename,line=$line_number::$message"
              # Increment the warning counter
              ((warning_count++))
            fi
          done < .markdownlintresult

          # Check if the warning threshold is exceeded
          if [[ $warning_count -gt $threshold ]]; then
            echo "Warning threshold exceeded. Stopping workflow."
            exit 1
  # Build job
  build:
    name: Build
    needs: [markdownLintCheck]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: false # to avoid Warning: "Restore cache failed: Dependencies file is not found in /home/runner/work/handbook/handbook. Supported file pattern: go.sum"
          go-version: ${{ env.GO_VERSION }}

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        if: success()
        run: sudo snap install dart-sass --channel=${{ env.DART_SASS_VERSION }}

      - name: Checkout
        if: success()
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        if: success()
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clear npm cache
        if: success()
        run: npm cache clean --force

      - name: Install Node.js dependencies with npm ci
        if: success()
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Update Hugo config
        if: success()
        run: |
          baseURL=${{ env.DEPLOYED_BASE_URL }}
          echo "baseURL: $baseURL"
          sed -i "s|baseURL[[:space:]]*=[[:space:]]*'.*'|baseURL = '$baseURL'|" hugo.toml

          baseName=${{ env.DEPLOYED_BASE_NAME }}
          echo "baseName: $baseName"
          sed -i "s|baseName[[:space:]]*=[[:space:]]*'.*'|baseName = '$baseName'|" hugo.toml

          buildDatetime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "buildDatetime: $buildDatetime"
          sed -i "s/buildDatetime[[:space:]]*=[[:space:]]*\".*\"/buildDatetime = \"$buildDatetime\"/" hugo.toml

          gitHash=$(git rev-parse --short HEAD)
          echo "git hash: $gitHash"
          sed -i "s/gitHash[[:space:]]*=[[:space:]]*\".*\"/gitHash = \"$gitHash\"/" hugo.toml

          version=$(grep 'version[[:space:]]*=' hugo.toml | sed 's/version[[:space:]]*=[[:space:]]*"\([^"]*\)"/\1/')
          echo "Current version: $version"

          branch_name=$(echo $GITHUB_REF | sed 's|refs/heads/||')
          echo "Current branch: $branch_name" 
          new_version="${version}+${branch_name}"
          echo "New version: $new_version"
          sed -i "s|version[[:space:]]*=[[:space:]]*\"${version}\"|version = \"${new_version}\"|" hugo.toml

      - name: Set Test style (blue lines)
        if: success()
        run: |
          sed -i "s|\$ob-venetian-red:[[:space:]]*#.*;|\$ob-venetian-red: #004ddc;|" assets/scss/_variables_project.scss

      - name: Build with Hugo
        if: success()
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
              --gc \
              --minify \
              --baseURL "${{ env.DEPLOYED_BASE_URL }}"

      - name: Copy README.md and LICENSE.md files in public directory
        if: success()
        run: |
          echo "This repository contents the built SpiGes-Documentation project website for testing" > README.md
          cp README.md public/
          cp LICENSE.md public/

      - name: Deploy to the specified environment
        # Runs only if:
        #   previous step successed
        #   AND the trigger is not a pull-request
        #   AND
        #     the trigger is automatic (push)
        #     OR the trigger is manual and 'deploymentEnabled' parameter is true
        if: success() && github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || github.event.inputs.deploymentEnabled == 'true')
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: ${{ env.TARGET_BRANCH }}
          build_dir: public
          repo: ${{ env.TARGET_REPOSITORY }}
          keep_history: ${{ env.KEEP_TARGET_HISTORY }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
