name: Generate node files (node_modules and package-lock.json) for a Windows environment

on:
  push:
    branches:
      - "**/*"
  workflow_dispatch:

env:
  NODE_VERSION: "20.12.1"

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install NPM dependencies
        run: npm install

      - name: Archive node_modules and package-lock.json
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: |
            node_modules
            package-lock.json
