# Build, Deploy Hugo site to Pages, Update Hugo Config, Create Release Draft, Publish Release
name: Release Documentation

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  verify_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify branch is 'main'
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: Workflow must be run on the 'main' branch."
            exit 1
          fi

  extract_release_version:
    needs: [verify_branch]
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.extract.outputs.release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract release version from hugo.toml
        if: success()
        id: extract
        run: |
          release_version=$(grep 'version[[:space:]]*=' hugo.toml | sed 's/version[[:space:]]*=[[:space:]]*"\([^"]*\)"/\1/')
          echo "Extracted version: $release_version"
          if [[ -z "$release_version" ]]; then
            echo "Release version is empty. Stopping the workflow."
            exit 1
          else
            echo "release_version=$release_version" >> $GITHUB_OUTPUT
          fi

  check_git_tag:
    needs: [extract_release_version]
    runs-on: ubuntu-latest
    if: always() && success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag exists
        if: success()
        env:
          RELEASE_VERSION: ${{ needs.extract_release_version.outputs.release_version }}
        run: |
          if git rev-parse "refs/tags/$RELEASE_VERSION" >/dev/null 2>&1; then
            echo "Tag $RELEASE_VERSION already exists."
            exit 1
          else
            echo "Tag $RELEASE_VERSION does not exist."
          fi

  read-tool-versions:
    uses: ./.github/workflows/read-tool-versions.yml

  # Build job
  build:
    needs: [check_git_tag, read-tool-versions]
    runs-on: ubuntu-latest
    if: always() && success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: false # to avoid Warning "Restore cache failed: Dependencies file is not found in /home/runner/work/handbook/handbook. Supported file pattern: go.sum"
          go-version: ${{ needs.read-tool-versions.outputs.go_version }}

      - name: Install Dart Sass
        uses: ./.github/actions/install-dart-sass
        with:
          dart_sass_version: ${{ needs.read-tool-versions.outputs.dart_sass_version }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.read-tool-versions.outputs.nodejs_version }}

      - name: Install dependencies
        run: npm ci

      - name: Update hugo.toml with build datetime and git hash
        run: |
          # Set the build datetime
          buildDatetime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s/buildDatetime[[:space:]]*=[[:space:]]*\".*\"/buildDatetime = \"$buildDatetime\"/" hugo.toml

          # Set the git hash
          gitHash=$(git rev-parse --short HEAD)
          sed -i "s/gitHash[[:space:]]*=[[:space:]]*\".*\"/gitHash = \"$gitHash\"/" hugo.toml

      - name: Build with Hugo
        env:
          BASE_URL: ${{ steps.pages.outputs.base_url }}
        run: npm run build:ci:production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: always() && success()
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-release:
    needs: [deploy, extract_release_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always() && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        env:
          RELEASE_VERSION: ${{ needs.extract_release_version.outputs.release_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "release version = $RELEASE_VERSION"
          gh release create "v$RELEASE_VERSION" --title "Release $RELEASE_VERSION" --notes-file RELEASE_NOTES.md --draft

  publish-release:
    needs: [create-release, extract_release_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always() && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Release
        env:
          RELEASE_VERSION: ${{ needs.extract_release_version.outputs.release_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "release version = $RELEASE_VERSION"
          gh release edit "v$RELEASE_VERSION" --draft=false
